########## Clients ##########

GET http://localhost:3000/api/clients

###
POST http://localhost:3000/api/clients
Content-Type: application/json

{
  "nombre": "Amapola",
  "apellidos": "Rodríguez",
  "direccion": "C/Amapola 5, Jaen",
  "telefono": "52581125", 
  "fecha_nacimiento": "1999-11-03", 
  "dni": "14785240H", 
  "email": "amapola@gmail.com"
}
###

PUT http://localhost:3000/api/clients/4
Content-Type: application/json

{
  "nombre": "Rosa",
  "apellidos": "Romero",
  "direccion": "C/Nispero 17, Huelva",
  "telefono": "787778512", 
  "fecha_nacimiento": "1994-08-28", 
  "dni": "15555777H", 
  "email": "rosa@gmail.com"
}

###

DELETE http://localhost:3000/api/clients/3

###

########## Travels ##########

GET http://localhost:3000/api/travels

###

POST http://localhost:3000/api/travels
Content-Type: application/json

{
  "fecha_salida":"2022-06-22 12:30" , 
  "fecha_vuelta": "2022-06-30 22:00", 
  "id_vuelo_ida": "4456U", 
  "id_vuelo_vuelta": "895UY", 
  "hotel_id": 3  
}

###

POST http://localhost:3000/api/travels/2/clients/5

###

PUT http://localhost:3000/api/travels/2
Content-Type: application/json

{
  "fecha_salida":"2022-05-22 12:30" , 
  "fecha_vuelta": "2022-05-30 22:00", 
  "id_vuelo_ida": "55WR8", 
  "id_vuelo_vuelta": "4456U", 
  "hotel_id": 4  
}

###

DELETE http://localhost:3000/api/travels/3

########## Hotels ##########

###
GET http://localhost:3000/api/hotels

###

POST http://localhost:3000/api/hotels
Content-Type: application/json

{
  "nombre": "Hotel la Libertad", 
  "direccion": "C/ Esperanza nº 2", 
  "ciudad": "Huelva", 
  "num_estrellas": 3, 
  "descripcion": "Hotel nudista", 
  "tarifa": 150  
}

###

PUT http://localhost:3000/api/hotels/2
Content-Type: application/json

{
  "nombre": "Hotel Chungo", 
  "direccion": "C/ Moho nº 20", 
  "ciudad": "Barcelona", 
  "num_estrellas": 1, 
  "descripcion": "Mira si hay cucarachas", 
  "tarifa": 5 
}

###

DELETE http://localhost:3000/api/hotels/3

